[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "unseen-formats"
version = "2025.0.0"
dependencies = [
  "manim",
  "matplotlib"
]
requires-python = ">=3.11"
